### ISSUE TITLE
Does it say how to import saves anywhere?

### ISSUE THREAD

**Issue by d0nt0n** [44670/desmume-wasm#102]
I have looked around but I can't find anywhere that it explains how to upload save files.

**Comment by 44670** [comment]
"Restore" button in the in-game menu.

**Comment by d0nt0n** [comment]
where is the restore button at? or is it different for every game?

**Comment by 44670** [comment]
In the in-game menu, you can access it by "Escape" in the keyboard, or "M" virtual button.
