### ISSUE TITLE
Cheats doesn’t work anymore

### ISSUE THREAD

**Issue by Lars2712** [44670/desmume-wasm#105]
The cheats were working but now the option disappeared .
Normally when i play Pokémon I had the option to choose between cheats but it disappeared and I don’t know how

**Comment by nonplayablecharacter77** [comment]
having same problem

**Comment by 44670** [comment]
It's in early access for now, you may have got 3 days for being invited.

**Comment by nonplayablecharacter77** [comment]
How do I get invited or use early access code ?

**Comment by 44670** [comment]
Patreon, it's also randomly issued in discord.
