### ISSUE TITLE
Mic support not strong enough, doesn’t fully blow whole screen

### ISSUE THREAD

**Issue by L1nco1n** [44670/desmume-wasm#109]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by 44670** [comment]
define blow whole screen?

**Comment by L1nco1n** [comment]
Basically, the puzzle in another code: two memories requires dust to be blown off a painting. The current mic function only blows a circle in the middle of the screen and then stops. Sadly the puzzles needs the whole rectangular shaped painting to be revealed so you can progress.

**Comment by 44670** [comment]
try press the 'R' key to emulate a blow

iphone's microphone has noise-canceling built-in

**Comment by L1nco1n** [comment]
I held down the R button constantly for half an hour and tapped it in short bursts, sadly it only blows a circle to a certain size and then stops :(

**Comment by L1nco1n** [comment]
![IMG_1247](https://user-images.githubusercontent.com/115383488/194743502-b94771a7-fa02-4eff-8846-588cdac21c22.png)

**Comment by 44670** [comment]
it's weird, does the game supposed to solve in this way btw? are there any walkthroughs?

**Comment by L1nco1n** [comment]
I’ve played through the game multiple times on an actual ds and it doesn’t blow the dust away like that. Here’s a picture from a walkthrough of how it’s meant to blow away.
![IMG_1251](https://user-images.githubusercontent.com/115383488/194769946-b6e7b081-e578-4d0a-80fb-bfa3377d9aa3.jpeg)

**Comment by 44670** [comment]
interesting, may follow this issue on my free time

**Comment by L1nco1n** [comment]
Cool! Hope you can figure it out! :)

**Comment by L1nco1n** [comment]
Thrilled to report the mic update has fixed this bug!
