### ISSUE TITLE
transfering data

### ISSUE THREAD

**Issue by RDahle** [44670/desmume-wasm#110]
hey. i am getting a new phone, but i wonder if its possible to transfer my saved game data to the new phone:)

**Comment by 44670** [comment]
yes it is possible, use 'backup' 'restore' buttons in the in-game menu.

**Comment by RDahle** [comment]
hey again. my old phone is broken so i can only see half the screen.. i got
to click back up, and got som message saying i have auto save so i dont
have to export data. i couldnt see the entire message but i just clicked
ok. then som other message came up where i couldnt see anything. but i just
clicked ok on that too... any help for me?..

**Comment by 44670** [comment]
you need type "Yes" for that, can you use a keyboard?

**Comment by RDahle** [comment]
i can barely see it but i think i wrote Yes now. whats next?

**Comment by 44670** [comment]
then you may save the .dsz file to the icloud

**Comment by RDahle** [comment]
yes i have done that and its on my new phone now, but wont his just open as
a new game then?

**Comment by 44670** [comment]
you have to import the dsz files using the "Restore" button......
