### ISSUE TITLE
I can’t load my saved files 

### ISSUE THREAD

**Issue by jameskk8** [44670/desmume-wasm#112]
For some reason when I load my saved files it says to close the app so I do, but when I load back on it just starts a new game. This is on the ds player on ISO. I have tried all the ways of closing and opening the file when loading it and nothing has changed

**Comment by 44670** [comment]
Where is your save file from?

By the way, have you ever saved in the game?

**Comment by jameskk8** [comment]
> I didn’t save in game I just saved the file from the menu and saved it to my files in my phone

**Comment by 44670** [comment]
You have to save in the game before exporting the save data lol...
