### ISSUE TITLE
Saves downloading in .dsz and unable to open in other emulators

### ISSUE THREAD

**Issue by Triplemcnugit** [44670/desmume-wasm#113]
**Describe the bug**
When I use the backup feature (I move between my ipad and computer, so I regularly download/upload my saves), the save downloads as a .dsz file. This file is unable to be opened by desmume, and when I change the file extension to .sav, the updated save that I did while playing on my ipad (using ds 44670) is reverted to the previous save that I uploaded before..

**To Reproduce**
1. Make a save using the in game save function (in this case in pokemon platinum's start menu)
2. ensure it loads properly in the emulator
3. use the menu and backup the save
4. save to accessible space (I tried google drive and the apple files app)
5. The file saves as a .dsz file, which can't be opened. Convert the file to .sav by renaming on a computer
6. The save is not updated and the same as any previously uploaded save

**Expected behavior**
The file would save as a .dst (desmume savestate format) or .sav (universal save file format)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox

**Smartphone (please complete the following information):**
 - Device: iPad air 5th generation
 - OS: 15.6.1
 - Browser: Safari

**Comment by 44670** [comment]
Use an archive tool to uncompress it.

**Comment by Triplemcnugit** [comment]
When I extract it or open it on 7zip, the only file is a file with no type and it cannot be opened by any program.

**Comment by 44670** [comment]
rename it to .dsv then
