### ISSUE TITLE
Keyboard won’t show up on iPad when I have to type “Yes” to save the game.

### ISSUE THREAD

**Issue by Migo194** [44670/desmume-wasm#124]

**Comment by 44670** [comment]
Tap the input box to use the keyboard.

https://support.apple.com/zh-cn/guide/ipad/ipad997da459/ipados

**Comment by 44670** [comment]
Tap the input box to use the keyboard.

https://support.apple.com/guide/ipad/type-with-the-onscreen-keyboard-ipad997da459/ipados
