### ISSUE TITLE
The saves files from this emulator are not compatible with any other emulator

### ISSUE THREAD

**Issue by FeroZero** [44670/desmume-wasm#126]
So basically i want to transfer my saves files(backup) to desmume for pc, but it doesnt detects it at all, and is beacuse the saves file have this extension call .dsz, i tried to convert it to .sav or .dsv but even if i do so, the desmume emulator cannot process the save file and gives an error.

i tried to using converting tools, doing it raw by just changing the name and look for videos but nothing changes, if yall can do a feature that the saves files can be converted to .sav or .dsv i bealive the issue can be solved, or if yall can tell me what to do in this situation i will also appreciated.

**Comment by 44670** [comment]
Just uncompress it with an acrhive utility (e.g.: 7zip), it's a compressed dsv file.
