### ISSUE TITLE
能否将存档文件弄成.sav之类的

### ISSUE THREAD

**Issue by JayCrusoe** [44670/desmume-wasm#128]
非常感谢作者的劳动，很棒的使用体验
因为想在PC上使用一些修改器，所以想问作者能否出一个功能可以将存档文件变成.sav.dat.nsd之类的后缀，让修改器能识别
感谢

**Comment by 44670** [comment]
可以用压缩工具解压成desmume的dsv格式。

修改器未必能使用，和真实机器的BIOS存在差异。

**Comment by JayCrusoe** [comment]
请问用什么软件可以解压？7zip和winrar都不行

**Comment by 44670** [comment]
.dsz格式可以用7zip解压。

**Comment by JayCrusoe** [comment]
不好意思再确认一下，存档文件是.4dsaz格式，重命名.dsz后也无法解压，是缺少了什么步骤？

**Comment by 44670** [comment]
这个在dropbox里的格式无法直接解压，可以导入dsplayer再导出，获得dsv格式。

**Comment by JayCrusoe** [comment]
可以使用了，感谢
