### ISSUE TITLE
Glitchy Audio

### ISSUE THREAD

**Issue by FlareGX8** [44670/desmume-wasm#134]
When playing You Don't Know Jack the audio seems to glitch out during questions, causing it to be kind of hard to understand hosts

**Comment by FlareGX8** [comment]
This ONLY seems to happen during questions, transitions between questions and intros seem to work fine, however whenever a host speaks for an extended time or reads off a question the audio bugs out, will post a video later

**Comment by FlareGX8** [comment]
Uploading IMG_2604.MOV…

**Comment by 44670** [comment]
what's your device? is low-power mode enabled?

**Comment by FlareGX8** [comment]
> what's your device? is low-power mode enabled?

I'm using an iPhone 12 Mini, this glitch seems to happen both with low power mode on and off.
