### ISSUE TITLE
Unplayable game

### ISSUE THREAD

**Issue by Pikachupikachup** [44670/desmume-wasm#142]
In The Legend if Zelda: Spirit Tracks the Start and Select buttons block the train left/right controls, so you can’t progress.

**Comment by 44670** [comment]
for that game you can hide the virtual gamepad in the menu

**Comment by Pikachupikachup** [comment]
But I am on mobile…

**Comment by 44670** [comment]
it's a touch screen the game, so you maybe you can hide it most times

**Comment by Pikachupikachup** [comment]
Ok
