### ISSUE TITLE
Trying to export data into dropbox not working

### ISSUE THREAD

**Issue by Rino6357** [44670/desmume-wasm#143]
I tried backing up the save manually as I could not find the save in the local files on my phone. It gave me a text prompt which I wasn't sure how to fill, but it didn't work. I tried uploading to dropbox and all I got was a folder with no .dsv files.

1. Save game
2. Connect dropbox
3. Upload to dropbox
4. Check newly added dropbox folder

I expected there to be a dsv file in the newly added folder, or clearer instructions on how to export the save.

![image](https://user-images.githubusercontent.com/60277295/229294171-0806bda0-d76b-47b5-be14-2fc687a8afc7.png)

Currently using an Iphone XR with safari.

The save I was using was first imported in the phone.

**Comment by 44670** [comment]
Please note that after carefully reading the instructions displayed in the attention popup when exporting the dsz file, selecting the option "Yes" will allow you to successfully export the dsz file.

Furthermore, clicking on "Upload" button will upload the 4dsaz file to the manual.4dsaz file in dropbox. The other files with numbers in the same folder represent the daily automatic backups.
