### ISSUE TITLE
Firmware

### ISSUE THREAD

**Issue by MajesticWafer** [44670/desmume-wasm#147]
Can you add an option to insert firmware? (This way you can't get sued by Nintendo because you are not giving out the firmware and so DS Download Play works, and Nintendo Wi-Fi Connection too)

**Comment by 44670** [comment]
Nope, this cannot suppor wfc even with firmware loaded, it's just a sandboxed web application in your browser lmao.

**Comment by 44670** [comment]
And please, don't create duplicated issues for wasting developers' time, thanks.
