### ISSUE TITLE
Games won’t load

### ISSUE THREAD

**Issue by BlackSwordsman124** [44670/desmume-wasm#154]
I have the application on my iPhone 14 and it runs fine. But I recently showed my brothers how to get it and add it to there Home Screen and now when they load up a ds Pokémon game like black and heart gold it shows the first to loading screens of the game and then nothing, just a black screen. It still works perfectly on my phone with the same game.

**Comment by 44670** [comment]
older iphone may have no enough memory, also ios needs to be latest.
