### ISSUE TITLE
Enabling Experimental Optimization is denied on iOS 17 Beta

### ISSUE THREAD

**Issue by Xolverr** [44670/desmume-wasm#156]
**Describe the bug**
When trying to enable experimental optimization while on iOS 17 Beta on the emulator, a message appears that you must be on iOS 16.4+.

**To Reproduce**
1. Enroll as an Apple Developer and install the iOS 17.0 Beta on your phone.
2. Install the emulator.
3. Try to enable experimental optimization.

**Smartphone**
 - Device: iPhone XR
 - OS: iOS 17.0 Beta 3
 - Browser: Safari
 - Version: v20230128

**Comment by QuaRang1225** [comment]
Is there no multi-touch function? While I was playing Last Window, I had to touch two buttons at once, but I think I only recognize one per touch

**Comment by 44670** [comment]
> Is there no multi-touch function? While I was playing Last Window, I had to touch two buttons at once, but I think I only recognize one per touch

https://www.reddit.com/r/Delta_Emulator/comments/r589cx/comment/joxv5ub/
