### ISSUE TITLE
any way to transfer pokemon black save from 44670 to an IRL ds?

### ISSUE THREAD

**Issue by DrSpaniel** [44670/desmume-wasm#157]
Hi! i finally got a ds, but now i would like to transfer my save file from 44670, to a dslite. (i have an r4 cart) i tried just transferring the file to an sd card, but it does not contain my save. and i think that the save files generated by 44670 are .4dsaz files, which i dont think can work with a DS. any idea how i can solve this?

**Comment by 44670** [comment]
Due to different BIOS implementations, it is not expected to work on real devices.
