### ISSUE TITLE
Pokemon Platinum ROM doesn't work,

### ISSUE THREAD

**Issue by zabbidou** [44670/desmume-wasm#159]
Hello, I have tried opening a ROM of Pokemon Platinum, but the emulator freezes on a white screen and that's it. The FPS counter is responsive, but nothing else moves.

I have added the website as an app in Safari on home screen and disabled the experimental feature I found somewhere in a readme.
Also, the file is .nds
If relevant, I am running on iPhone 13 Pro on IOS 16.5.1

**Comment by 44670** [comment]
If the file can't be opened on Chrome for PC. It's game file's problem, please ensure you have the genuine game card and dumped it correctly.
