### ISSUE TITLE
Ace Attorney games not saving?

### ISSUE THREAD

**Issue by MrDawe** [44670/desmume-wasm#16]
I have been trying to play a couple of Ace Attorney games (Ace Attorney Investigations: Miles Edgeworth and Phoenix Wright: Ace Attorney) and they are not saving, even if the saving notification appears on screen. 

This doesn’t seem to affect any other games. I know save states are available but either I don’t know how to use them or they don’t work for me either. 

In any case, thank you for your fantastic work!

**Comment by MrDawe** [comment]
Thank you for looking into this!

**Comment by 44670** [comment]
Please comment on this issue again, if it still happens.
