### ISSUE TITLE
Pokémon Platinum Freezing

### ISSUE THREAD

**Issue by caydjj** [44670/desmume-wasm#171]
**Describe the bug**
While playing Pokemon Platinum, the gameplay completely freezes at the same point each time. Audio continues, button inputs are registered (though don’t do anything), and everything else about the app continues functioning.

**To Reproduce**
In Pokemon Platinum, reach the fight with Mars and Jupiter on Mt. Coronet. 
After the battle is completed, watch the cutscene while Cyrus attempts to bring Palkia and Dialga to Mt. Coronet. The audio and visuals should start to desynchronize here, as you can hear Palkia and Dialga’s cries and what sounds to be them landing on the ground, yet there is no visual indication that they are there.
Now, the game should be “frozen” waiting for the two Pokemon to spawn. Audio continues in the game, but controls do nothing and the game gets stuck here.

**Expected behavior**
Palkia and Dialga spawn and the game continues as normal, starting the fight with Cyrus.

**Smartphone (please complete the following information):**
 - Device: iPhone 15 Pro Max
 - OS: iOS 17.2.1
 - Browser: Safari, saved to Home Screen 
 - Version: default

**Comment by caydjj** [comment]
It looks like there have been others encountering this issue recently as well: https://forums.desmume.org/viewtopic.php?id=12554

**Comment by 44670** [comment]
Maybe the game file is corrupted, please ensure you dumped them from a genuine game card.

**Comment by caydjj** [comment]
The game file is not corrupted, as the same file has been used previously with other emulators with no issue. Is there any way to extract the save file to test this save with this game file in a desktop version of Desmume?

**Comment by 44670** [comment]
Yes you can unzip it to dsv.

**Comment by 44670** [comment]
Please note only original files dumped fron genuine game card by yourself works, even the file works on other emulators, it may not work here if it's a patched/modded file.
