### ISSUE TITLE
custom display options for bottom and top screen

### ISSUE THREAD

**Issue by obscurerev** [44670/desmume-wasm#40]
for example, presets with only the top screen only showing, bottom screen only showing or side by side.

**Comment by 44670** [comment]
working on it

**Comment by obscurerev** [comment]
to kinda elaborate, show the top screen bigger and the touch screen smaller, or remove touch screen entirely

**Comment by feljx** [comment]
I'm super interested in side-by-side display on my phone.
Maybe I can help somehow with development, could you give a hint where to start looking?

**Comment by 44670** [comment]
Done.
