### ISSUE TITLE
Is it possible to use your own mic to play a game?

### ISSUE THREAD

**Issue by Unzor** [44670/desmume-wasm#42]
Hello,
I am currently trying to play Nintendogs, but I need to use the mic for it. Is there a way that my mic could be used?
Thanks!

**Comment by 44670** [comment]
Not supported for now.

**Comment by glitch128** [comment]
do you have an idea when it will be implemented?

**Comment by 44670** [comment]
I have some considerations about privacy, maybe it will be an early access feature that requires user consent.

**Comment by Unzor** [comment]
Maybe you can:
- First, consent user for microphone access
- When E pressed, get audio from mic and send it to the emulator

**Comment by 44670** [comment]
Now available as an EA feature, however it still have some issues.

**Comment by glitch128** [comment]
how do I get early access?

**Comment by 44670** [comment]
you can get EA features by inviting
