### ISSUE TITLE
the ads

### ISSUE THREAD

**Issue by Grumm1291** [44670/desmume-wasm#49]
The ads thing has ruined the website and the sharing feature doesnt work, we put this on an emulator website for school and the ads break it, please remove them as this is a really bad way to squeeze moneys out of people who just want to play ds games

**Comment by RunTheCoins** [comment]
I don't see any ads? can you send me a screenshot of what your talking about?

**Comment by 44670** [comment]
OK, I have removed the intrusive ads now.

**Comment by 44670** [comment]
Sharing feature may not work if the devices are sharing same network connection.

In this case, I can offer ad-free and 14-days early access for your school. Is that website public available?

**Comment by BypassGoGuardianPLS** [comment]
> Sharing feature may not work if the devices are sharing same network connection.
> 
> In this case, I can offer ad-free and 14-days early access for all the new users from your school. Is that website public available?

No the website is not public, running on schools drive server. People outside the google organization dont have access.

**Comment by BypassGoGuardianPLS** [comment]
Adding on to my friends thing, sharing feature is cool, but you're already running with ads, so the share feature would be more useful if it unlocked unique skins or other things that dont affect emulation.

**Comment by 44670** [comment]
Now there are two early features available, which can be unlocked by sharing.

Skins is a good idea if I am able to pay for a designer.
