### ISSUE TITLE
GBA Player not playing any roms at all

### ISSUE THREAD

**Issue by obscurerev** [44670/desmume-wasm#51]
doesn't even load any gba game

**Comment by obscurerev** [comment]
oh i saw it was updated just today so sorry if you are still working on it

**Comment by 44670** [comment]
Is this one workable? https://44670.org/gba

**Comment by obscurerev** [comment]
it ain't loading i've waited for a minute

**Comment by obscurerev** [comment]
only the homebrew games work

**Comment by 44670** [comment]
It might be the problem with your file, only .gba is supported.
