### ISSUE TITLE
Auto save banner

### ISSUE THREAD

**Issue by Tuley000** [44670/desmume-wasm#53]
When the auto save banner is shown, does this mean whenever you load up that rom the data will be saved and you can continue where you were? Also do we wait after we export data for the banner to show?

**Comment by 44670** [comment]
Auto save banner shows on every time your save data is storing into the local storage. It is not related to the game file you loaded.

It is recommended to export data after the banner disappeared.

**Comment by Tuley000** [comment]
Is there a way to start an auto save? When does the banner show up?

**Comment by 44670** [comment]
It shows up when you save in the game. You don't need to start it.

**Comment by Tuley000** [comment]
Ok thanks
