### ISSUE TITLE
Embeddable version

### ISSUE THREAD

**Issue by Unzor** [44670/desmume-wasm#54]
I have made an embeddable version of DeSmuME-wasm, and I was wondering if you could add this in the description for anyone who wants to embed it. The name is [Desmond](https://github.com/js-emulators/desmond), and I have given credits to your project. Could you add it or should I take it down?

Link:
https://github.com/js-emulators/desmond

**Comment by 44670** [comment]
It is recommended to use a homebrew application as a demo.

**Comment by Unzor** [comment]
It is not obfuscated, it is minimized. I can publish the beautified version in /dist as desmond.js if you want.

**Comment by 44670** [comment]
I guess an original version your write is required for open source projects.

I won't add this link because I can't granturee it will work.

**Comment by Unzor** [comment]
Fair enough, although it does work. Closing this.

**Comment by 44670** [comment]
It is an unacceptable behavior to host rom files on your server and let DS Player loads them.

To be clear, this software should not be used to play games you have not legally obtained. It is OK if the user chooses his own files he has legally obtained. It is also OK to load a free homebrew game on a web server. However, it is NOT OK to directly load roms from server.

You have already been warned and looks like you (or your friend) are still trying this in another way, which make this project in danger of being taken-down if this behavior continues.

It is not called an open-source project if you just copy-paste other people's code and bundle it with games you have no copyright on.

Please, don't do this.
