### ISSUE TITLE
Wifi Support 

### ISSUE THREAD

**Issue by olijeffers0n** [44670/desmume-wasm#56]
Hi there, i am interested in local multiplayer and save files. I am currently using Desmond https://github.com/js-emulators/desmond to embed it in my site, but i have seen in my console that "WIFI: Emulation level is OFF.". I am trying to use the wifi play with my friends for a local multiplayer mario kart, as well as maybe saving files. Can you offer any details? 

This has been working very well though so far!

Thanks

**Comment by 44670** [comment]
It is possible to save in ds.44670.org as long as you have add it to home screen.

Desmond is a rebranded an obfuscated version of desmume-wasm AFAIK, it copies the code from this project, removed saving features and obfuscated it. I can't see what the author's motivation is for removing the saving feature, nor can I help.

Looks like wifi is supported in desmume, https://github.com/TASEmulators/desmume/blob/master/desmume/src/wifi.cpp, but it is not possible to use this directly in the browser.
