### ISSUE TITLE
Access was denied

### ISSUE THREAD

**Issue by Ghirrahim** [44670/desmume-wasm#58]
> Access was denied Error code 1020
> You do not have access to ds.44670.org.
>The site owner may have set restrictions that prevent you from accessing the site. Contact the site owner for access or try loading the page again.

Seem's I can't access the site anymore. Not sure if I was blacklisted but it can be used by using the proxy

**Comment by 44670** [comment]
The firewall may block clients for sending automated requests.
In this case I have added a temporary whitelist, if this problem still happen in future, it is advised to do a malware scan.

**Comment by Ghirrahim** [comment]
Alright, Thanks.
