### ISSUE TITLE
Ads Break my game,

### ISSUE THREAD

**Issue by AveriVann16-57** [44670/desmume-wasm#59]
I play on the chromebook, and i have been a long time player of this game, PLEASE, Remove the adds! I will pay you a one time payment! I just wanna play drayanos new pokemon rom hack...

**Comment by AveriVann16-57** [comment]
FOrgot to state how the dont let me play at all

**Comment by 44670** [comment]
Which AD did you seen? It should just some amazon items in the loading page which is impossible to break games. Threre are absoulutely no ADs in gameplay.

**Comment by AveriVann16-57** [comment]
the actual website, sorry, it was my rom, nvm,
