### ISSUE TITLE
Ideas for the emulator

### ISSUE THREAD

**Issue by skygames23** [44670/desmume-wasm#6]
-Speed button
-Possibility of changing the size of the buttons
-Possibility of using cheats

**Comment by RunTheCoins** [comment]
also It would be cool if you can change the size of the screen for like a widescreen cheat code, as I feel as it is small.

**Comment by EBmang101** [comment]
I would love there to be skins so we know which button to press I also want the skins for customization 😂 but great Emulator! Runs so smooth on a app browser called opera Gx

**Comment by 44670** [comment]
Duplicate of #12 #21
