### ISSUE TITLE
Allow use of the emulator when not connected to the internet

### ISSUE THREAD

**Issue by Gamerfiend** [44670/desmume-wasm#61]
I was wondering if you think it would be possible to implement the use of the emulator offline on iPadOS/iOS through the use of service workers? 

https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Offline_Service_workers

**Comment by 44670** [comment]
Yes, it is possible!
I guess offer offline access will be available after first stable version.

**Comment by chief18** [comment]
Hello! Totally waiting for this, may should be one the most important in these updates together with the D-Pad
Also consider that another one important web-based iOS emulator, Eclipsemu (which is just GBA and a little too much buggy), if this can help.
Thank you!

**Comment by 44670** [comment]
Offline mode is supported now!

**Comment by chief18** [comment]
> Offline mode is supported now!

Thank you so much!!!!
