### ISSUE TITLE
Rom Hack not working?

### ISSUE THREAD

**Issue by Flamiina** [44670/desmume-wasm#66]
I tried to run the Rom hack Pokemon Volt White 2 Redux, and the website just does not do anything when I try to open the file. I have tried waiting and nothing happens. Is there is a size limit to a rom? It is in a .nds file format, however the website does not say that it isn't support like other file types. I would really like to play it on my phone, so I can take my game wherever I go!

**Comment by Cha0t1cDX** [comment]
Pokemon White 2 is a 3DS game(3DS doesn't work on this :( ), and Volt White 2 Redux of pokemon White 2, so it won't work unfortunatly.

**Comment by Flamiina** [comment]
Ah I just completely blanked, thank you so much

**Comment by AveriVann16-57** [comment]
ITs a DS Rom!

**Comment by Cha0t1cDX** [comment]
Listen. Pokemon WHITE&BLACK(not the remakes) Work on this. Pokemon White2 & Black2 DON'T(DO NOT) WORK on this emulator.

**Comment by 44670** [comment]
Probably fixed.

**Comment by Cha0t1cDX** [comment]
'ccording to AveriVann 16-57 it's workin'

**Comment by 44670** [comment]
I assume it was fixed, closing this.

**Comment by Cha0t1cDX** [comment]
Tried it- and didn't work, odd.

**Comment by AveriVann16-57** [comment]
Tried it and it worked

**Comment by Cha0t1cDX** [comment]
huh it just might be only on my part... when I open black 2 roms and such, it doesn't load. It only stays on the same page.
