### ISSUE TITLE
Guide: Frequently asked questions

### ISSUE THREAD

**Issue by Cha0t1cDX** [44670/desmume-wasm#68]
### **Hey! This is a guide on how this works, if you have an error that isn't on this list, MAKE A ISSUE!**
Ok! Let's start it off;
**NDS ROM HACK NOT WORKING**(From #66 & #60): CHECK THE ROM! MAKE SURE IT'S A .NDS FILE. If it still doesn't work and it's a .NDS file, make an issue.

**GBA FILE NOT WORKING**(from #51) ONLY GBA IS SUPPORTED. MAKE SURE IT'S A .GBA FILE If it still doesn't work and it's a .GBA file, make an issue.

**KEYBIND CUSTOMIZATION** #15 

**HOW TO SAVE**(from #64 #52 #36 #38 #25 #22 #17 & #10): Only the .dsv file is supported. To save save in the game, and wait a few seconds, then click EXPORT. When you import it, it sends you back to the menu screen, click “CONTINUE”.

**Cheat codes**(FROM #29 #21 & #25): It's now in Early Access(EA). Stop asking for it, wait for the release.

**Can I download it and run it as an HTML**(from #27 & #31): Short answer: no.
Long answer: Most browsers will refuse to load local wasm files. So a http server is needed.
If python 3 is installed on your system, you can use it with python `-m http.server`. 
Just download all the files and open it with your browser, it may work.
Tried downloading and running locally. But it is missing the folder "build" with nds.js file. Also downloaded that from the published version but got a CORS error. Any advice?I am unsure what the case is for the python http server. However, if you are getting a CORS error, this is how I was able to launch with Node/npm and the [http-server](https://www.npmjs.com/package/http-server) module.`npx http-server --cors=http://localhost:8080/ -o` .I believe this is needed only when browsers correctly (?) enforce same-origin policy, as it is outlined in the [WebAssembly Security documentation](https://webassembly.org/docs/security/). Additionally, each module is subject to the security policies of its embedding. Within a [web browser](https://webassembly.org/docs/web/), this includes restrictions on information flow through [same-origin policy](https://www.w3.org/Security/wiki/Same_Origin_Policy). On a [non-web](https://webassembly.org/docs/non-web/) platform, this could include the POSIX security model. Keep in mind that if you are going to load files (beyond the nds.wasm) from another domain, you should update the CORS policy from the localhost version I posted.- 44670 & musotec  **_( Look I got lazy)_**

**LIMITING FPS**(#29):Select power mode in the menu.

Tell me if anything new has been solved, if not, I'll probably scavenge this project trying to find things I can solve.
Tired and dull, -DX

**Comment by 44670** [comment]
Closing this, a FAQ list in the readme will be added.
