### ISSUE TITLE
Improve and Optimize for FPS

### ISSUE THREAD

**Issue by Consumedgrub2** [44670/desmume-wasm#69]
The emulator runs slow in general, even though I believe it should be possible to run at least 20 - 30 FPS even on a toaster (Regardless of power saving mode on or off), however on a weaker laptop, that is about 2 years old from today (Of course running an up-to-date modern web browser), it runs at 3 - 5 FPS. Is it possible to optimize whats under the hood? I saw [this issue](https://github.com/44670/desmume-wasm/issues/63) before posting, and it seems the emulator has gotten slower after an update with ads.

**Comment by Cha0t1cDX** [comment]
first off, if you're on your own laptop, download DeSmuMe/MelonDS- And have you tried closing tabs &/or apps?

**Comment by Consumedgrub2** [comment]
Yes, I've tried this with all background processes and tabs closed, and also secondly, I am just trying a web port to see how far web apps and emulators progressed with javascript and web assembly, so of course I would mainly play on desume itself, and not this web assembly port. As for the comp specs issue; after doing further research, I've tested on multiple machines and even on a Ryzen 7 2700x rig and still have had some drops to 13 FPS with power save mode off on Intense games like the DS zelda titles. Now I know this is some crazy good emulator and I shouldn't go into it expecting the performance of Desume running on a desktop environment instead of the browser, but I just wondering if the performance could possibly be improved somehow, by whatever means.

**Comment by 44670** [comment]
Did you play at https://ds.44670.org or other sites?
An AMD 3800X Windows PC with latest Chrome could run most 3d games at 60fps. A 2700X computer shouldn't have such low performance, maybe it's an OS/browser issue?

**Comment by Consumedgrub2** [comment]
You may be right, after all though I am running TLOZ: Spirit tracks which is probably one of the most graphically intensive games for the DS.

**Comment by 44670** [comment]
What's the OS and browser?
