### ISSUE TITLE
Microphone not working

### ISSUE THREAD

**Issue by gabrl12345678900** [44670/desmume-wasm#72]
I tried to play a game that uses the microphone but it dosen't receives any sounds  

When you press RL with the microphone ready it should take the sounds from the microphone 

 - Device: IPhone XR 
 - OS: IOS 15.5
 - Browser safari
 - Version 15.4

**Comment by 44670** [comment]
Pressing R will send a noice to emulated microphone to emulate a blow.

Using device's own microphone is an early access feature for now.
