### ISSUE TITLE
Mic not working

### ISSUE THREAD

**Issue by Bobthegodofall** [44670/desmume-wasm#73]
My mic isn't working. I'm on an iphone SE, iOS 15.5, and when I hold down the R button on the virtual keyboard, the mic only picks up static. I've attempted to check my microphone through voice memos, and it appears to work fine. Same goes for discord. I made sure I allowed mic permissions and checked to see the microphones on the phone were clean. Nothing seemed to work.

**Comment by 44670** [comment]
It is an expected behavior, pressing R will send a noise to emulated microphone to emulate a blow.

Using device's own microphone is an early access feature for now.
