### ISSUE TITLE
speedup

### ISSUE THREAD

**Issue by bckdoo** [44670/desmume-wasm#76]
**Have you confirmed that there are no existing issues for this feature?**
Before submitting a feature request, please make sure there are **NO** existing requests for that feature in the issue list.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bckdoo** [comment]
Can i speed up the game play?

**Comment by 44670** [comment]
It's under consideration, might be able to do that on iPhone 13+.

**Comment by 44670** [comment]
It has been added in early access, iPhone 12+ is required I guess.

**Comment by paeifbnaeufbpae** [comment]
This feature still isn’t available, is it? Or do I still need an early access code?

**Comment by 44670** [comment]
Yep it is in beta testing, and may not work properly on some devices.
