### ISSUE TITLE
How can i activate The Turbo Mode ?

### ISSUE THREAD

**Issue by naydraz** [44670/desmume-wasm#78]
**Have you confirmed that there are no existing issues for this feature?**
Before submitting a feature request, please make sure there are **NO** existing requests for that feature in the issue list.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by naydraz** [comment]
I have the iPhone 13 pro Max

**Comment by 44670** [comment]
It's an early access feature, could be activated by inviting.
