### ISSUE TITLE
Merge the GBA player with the NDS player

### ISSUE THREAD

**Issue by YashChavan999** [44670/desmume-wasm#79]
It would be nice to have the GBA player either updated or integrated with the NDS player. The GBA player doesn't have some of the NDS player's features like exporting/importing saves and playing offline.

**Comment by 44670** [comment]
You can export savegames in GBA player, just like the DS one.

Playing offline will be added when it is out of experimental state.

No, it won't be merged since the consoles and our codebase are totally different.

**Comment by YashChavan999** [comment]
Thanks for the fast reply. This project is really cool.
