### ISSUE TITLE
Export save to different emulator?

### ISSUE THREAD

**Issue by jonahb360** [44670/desmume-wasm#89]
Hi,

I was wondering if there's any way to move a savefile from the WASM port to a different emulator (Desmume or MelonDS). I've been loving your port on my phone, but my laptop is very old and other emulators perform better on it. It doesn't seem like the 4Dsaz file WASM exports is import compatible - would there be a way for me to get access to a raw .sav file, a .dsv file, or convert the 4dsaz file somehow?

Many thanks!

**Comment by 44670** [comment]
It's in dsv format in localstorage, please note that it may have issues if being used in different emulators since the bios implementations are different.
