### ISSUE TITLE
Hi-Res emulation Ability 

### ISSUE THREAD

**Issue by RunTheCoins** [44670/desmume-wasm#9]
It would be cool for the emulator to have the HI Resolution add-on, as it would make it look a lot better

**Comment by GeTuck** [comment]
Hello RunTheCoins, it's me 3DSdev aka GerekRulesGwof from Scratch!

**Comment by RunTheCoins** [comment]
Oh hello!, oof I need to be more active here

**Comment by 44670** [comment]
xbrz upscaler has been added
