### ISSUE TITLE
话说大佬为什么不直接公开wasm

### ISSUE THREAD

**Issue by nenge123** [44670/desmume-wasm#90]
我想用在我的最新构思，这个有没有保留retroarch界面，还有能不能让他支持中文正常显示？
https://nenge.gitee.io/retroarch-web/

**Comment by 44670** [comment]
可以自行编译。

RetroArch自己有web port：https://web.libretro.com/

**Comment by nenge123** [comment]
不会啊，也试过搭环境，当然报错的。而是官方漏了nds没有编译

**Comment by 44670** [comment]
这个项目不是基于rarch框架的，可以试试这个基于rarch的。
https://github.com/BinBashBanana/webretro
