### ISSUE TITLE
Local Wireless Compatibility with Real DS/3DS Hardware?

### ISSUE THREAD

**Issue by ReynavaQueen** [44670/desmume-wasm#92]
I would honestly love if my brother could be able to visit my Animal Crossing Wild World town, but with several tries, I unfortunately can’t invite him, or visit his town.

Could there possibly be any way to replicate the DS/3DS's Local Wireless Connection with the emulator by chance?

**Comment by 44670** [comment]
Nope, a web app has not such ability for that.
