### ISSUE TITLE
Export save file not working in other emulators.

### ISSUE THREAD

**Issue by Cammeran430** [44670/desmume-wasm#93]
**Describe the bug**
I am able to open .sav files on the emulator, but when I export save files, it saves as a .dsz file instead of a .dsv or .sav file. Every emulator I tried to open the save on does not recognize the file type. 

**To Reproduce**
1. Open Pokémon platinum and save the game at the first opportunity.
2. Export the save and look at the file extension.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iphone 11
 - OS: 15.6
 - Browser: Safari

**Additional context**

**Comment by 44670** [comment]
It needs to be uncompressed, please note that due to difference between different bios implementations, it may not compatible in other emulators and may cause issues.
