### ISSUE TITLE
Import save data problem

### ISSUE THREAD

**Issue by Timdxg** [44670/desmume-wasm#94]
On ds player(iOS version), when I import my game save data manually using my save file, it sends me back to the menu and continuously says loading so I can’t load the game back up. How do I fix this?

**Comment by 44670** [comment]
Where do your save file from, what's the file name?

**Comment by Timdxg** [comment]
> Where do your save file from, what's the file name?

My save files are from ds.44670.org, and save file is a .dsv file.

**Comment by 44670** [comment]
the save data has been loaded if you have saved in the game before exporting, just quit & reopen the app.
