### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by HunterBoy344** [44670/desmume-wasm#97]
I've been trying to compile the latest version from source for the past two hours. I just can't get it to compile. Here's a snippet of the error when running `emmake make CXXFLAGS=-I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -lglib-2.0`

```
In file included from commandline.cpp:20:
In file included from /usr/include/glib-2.0/glib.h:30:
In file included from /usr/include/glib-2.0/glib/galloca.h:32:
/usr/include/glib-2.0/glib/gtypes.h:423:3: error: '_GStaticAssertCompileTimeAssertion_0' declared as an array with a negative size
  G_STATIC_ASSERT(sizeof (unsigned long long) == sizeof (guint64));
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/glib-2.0/glib/gmacros.h:277:103: note: expanded from macro 'G_STATIC_ASSERT'
#define G_STATIC_ASSERT(expr) typedef char G_PASTE (_GStaticAssertCompileTimeAssertion_, __COUNTER__)[(expr) ? 1 : -1] G_GNUC_UNUSED
                                                                                                      ^~~~~~~~~~~~~~~
In file included from commandline.cpp:25:
In file included from ./movie.h:28:
./utils/datetime.h:678:11: warning: left operand of comma operator has no effect [-Wunused-value]
                temp = (year, month, day);
                        ^~~~
./utils/datetime.h:678:17: warning: left operand of comma operator has no effect [-Wunused-value]
                temp = (year, month, day);
                              ^~~~~
2 warnings and 1 error generated.
em++: error: '/root/StuntsMultiplayer/emsdk/upstream/bin/clang++ -target wasm32-unknown-emscripten -DEMSCRIPTEN -D__EMSCRIPTEN_major__=3 -D__EMSCRIPTEN_minor__=1 -D__EMSCRIPTEN_tiny__=14 -fignore-exceptions -fvisibility=default -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -Werror=implicit-function-declaration -Xclang -iwithsysroot/include/SDL --sysroot=/root/StuntsMultiplayer/emsdk/upstream/emscripten/cache/sysroot -Xclang -iwithsysroot/include/compat -DPACKAGE_NAME="desmume" -DPACKAGE_TARNAME="desmume" -DPACKAGE_VERSION="0.9.9" "-DPACKAGE_STRING=\"desmume 0.9.9\"" -DPACKAGE_BUGREPORT="" -DPACKAGE_URL="" -DPACKAGE="desmume" -DVERSION="0.9.9" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DSVN_REV="r0" -DHAVE_LIBZ=1 -DHAVE_GL_GL_H=1 -DHAVE_GL_GLU_H=1 -DHAVE_LIBDL=1 -DHAVE_LIBGL=1 -DFAKE_MIC=1 -DHAVE_JIT=1 -I. -I../src -I/usr/include/glib-2.0 -MT commandline.o -MD -MP -MF .deps/commandline.Tpo -c commandline.cpp -o commandline.o' failed (returned 1)
make[2]: *** [Makefile:1263: commandline.o] Error 1
make[2]: Leaving directory '/root/StuntsMultiplayer/desmume-wasm/desmume/src'
make[1]: *** [Makefile:1285: all-recursive] Error 1
make[1]: Leaving directory '/root/StuntsMultiplayer/desmume-wasm/desmume/src'
make: *** [Makefile:432: all-recursive] Error 1
emmake: error: 'make CXXFLAGS=-I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -lglib-2.0' failed (returned 2)
```
Please help me I am at my wit's end, nothing is working and I want die please help

**Comment by 44670** [comment]
You should not use that makefile, it's for desktop builds and require libraries that are not available in emscripten.

Using the cmake file may be a good start.

**Comment by HunterBoy344** [comment]
Okay, first, I wasn’t being serious about the “I want die” part, so it’s all good

I do have one more question, though. I tried using the files from the official site (`ds.44670.org`) to host locally (including nds.wasm). However, when I tried using an HTTP server to access the downloaded site, I simply was redirected from `localhost:8000` to `ds.44670.org`. I tried again, this time using `127.0.0.1:8000`, and it worked perfectly. Hosting it on Replit produces the same results as using `localhost`.

Is there a way to remove the redirect @44670? I don’t want to use the original site because I want to run a specific game, add custom functions, etc.

**Comment by 44670** [comment]
Sorry, this project cannot be used to load roms from online server. The web server have added that limitation for preventing it from being used for malicious purposes (like piracy). 

"I want to die" is not an appropriate joke, and please do not do this to others.

**Comment by HunterBoy344** [comment]
I’m not loading ROMs from an external server. I’m trying to host the emulator on `localhost`.

**Comment by HunterBoy344** [comment]
Okay, I’ve just decided to compile for myself. When running `emmake cmake .` in the `wasm-port` directory, I receive an error that `decrypt.cpp` is missing. I tried using the one from official desmume but it gave me an error. Any help @44670?

**Comment by 44670** [comment]
Please don't flood in the discord server, that are not for such discussion, thanks.

You should not bundle this project with a commercial game, no matter if it is for your personal use.
