### ISSUE TITLE
Support closing the lid

### ISSUE THREAD

**Issue by Bools101** [44670/desmume-wasm#98]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Bools101** [comment]
> Do you mean closing the lid?
Yes

**Comment by Bools101** [comment]
Yes

**Comment by chris1794** [comment]
> Yes
> […](#)

did you find out how it works?

**Comment by L1nco1n** [comment]
Any updates on this?

**Comment by 44670** [comment]
Updated, now you can close the lid in the menu.
